# Generated by Django 4.2.16 on 2024-12-14 08:50

from django.db import migrations, models
import media_uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_uploader', '0002_file_upload_date_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(upload_to=media_uploader.models.generate_unique_filename),
        ),
    ]
